# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/kmd17/documents/github/embedded_systems_lab3_customip/customip.tmp/led_ip_v1_0_v1_0_project/led_ip_v1_0_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/kmd17/documents/github/embedded_systems_lab3_customip/customip.tmp/led_ip_v1_0_v1_0_project/led_ip_v1_0_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab3_CustomIP/ip_repo/GRAY_ACCELERATOR_1.0
  c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab3_CustomIP/ip_repo
} [current_project]
set_property ip_output_repo c:/users/kmd17/documents/github/embedded_systems_lab3_customip/customip.tmp/led_ip_v1_0_v1_0_project/led_ip_v1_0_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab3_CustomIP/ip_repo/led_ip_1.0/hdl/led_ip_v1_0_S_AXI.v
  c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab3_CustomIP/ip_repo/led_ip_1.0/hdl/led_ip_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top led_ip_v1_0 -part xc7z020clg484-1


write_checkpoint -force -noxdef led_ip_v1_0.dcp

catch { report_utilization -file led_ip_v1_0_utilization_synth.rpt -pb led_ip_v1_0_utilization_synth.pb }
